"""Protocol definition for OmniVoice worker execution backends."""

from __future__ import annotations

from typing import Any, Protocol


class OmniBackend(Protocol):
    """Protocol for OmniVoice backend implementations (Real vs Mock)."""

    def ping(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def runtime_info(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def load_model(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def unload_model(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def synthesize(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def create_voice_prompt(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def validate_voice_prompt(self, params: dict[str, Any]) -> dict[str, Any]: ...

    def shutdown(self, params: dict[str, Any]) -> dict[str, Any]: ...
