/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VieneuRouteImport } from './routes/vieneu'
import { Route as VoicesRouteImport } from './routes/voices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VieneuRoute = VieneuRouteImport.update({
  id: '/vieneu',
  path: '/vieneu',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/scripts': typeof ScriptsRoute
  '/settings': typeof SettingsRoute
  '/vieneu': typeof VieneuRoute
  '/voices': typeof VoicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/scripts': typeof ScriptsRoute
  '/settings': typeof SettingsRoute
  '/vieneu': typeof VieneuRoute
  '/voices': typeof VoicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/scripts': typeof ScriptsRoute
  '/settings': typeof SettingsRoute
  '/vieneu': typeof VieneuRoute
  '/voices': typeof VoicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history' | '/scripts' | '/settings' | '/vieneu' | '/voices'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/scripts' | '/settings' | '/vieneu' | '/voices'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/scripts'
    | '/settings'
    | '/vieneu'
    | '/voices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  ScriptsRoute: typeof ScriptsRoute
  SettingsRoute: typeof SettingsRoute
  VieneuRoute: typeof VieneuRoute
  VoicesRoute: typeof VoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vieneu': {
      id: '/vieneu'
      path: '/vieneu'
      fullPath: '/vieneu'
      preLoaderRoute: typeof VieneuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  ScriptsRoute: ScriptsRoute,
  SettingsRoute: SettingsRoute,
  VieneuRoute: VieneuRoute,
  VoicesRoute: VoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
