"""add export fields

Revision ID: 1570f2fe225e
Revises: 62f59f77359a
Create Date: 2026-08-05 19:04:31.845878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1570f2fe225e'
down_revision: Union[str, Sequence[str], None] = '62f59f77359a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col['name'] for col in inspector.get_columns('tts_jobs')]
    if 'export_path' not in columns:
        op.add_column('tts_jobs', sa.Column('export_path', sa.Text(), nullable=True))
    if 'export_format' not in columns:
        op.add_column('tts_jobs', sa.Column('export_format', sa.String(length=10), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tts_jobs', 'export_format')
    op.drop_column('tts_jobs', 'export_path')
    # ### end Alembic commands ###
