"""add custom voices table

Revision ID: 62f59f77359a
Revises: a3f1c9d2e7b4
Create Date: 2026-08-05 17:08:03.835705

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62f59f77359a'
down_revision: str | Sequence[str] | None = 'a3f1c9d2e7b4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'tts_custom_voices' not in inspector.get_table_names():
        op.create_table(
            'tts_custom_voices',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('display_name', sa.String(length=255), nullable=False),
            sa.Column('reference_audio_path', sa.String(length=1024), nullable=False),
            sa.Column('transcript', sa.Text(), nullable=False),
            sa.Column('consent_given', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tts_custom_voices')
    # ### end Alembic commands ###
